/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scouting_application;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 20iyerd
 */
public class ScoutingUI extends javax.swing.JFrame {

    /**
     * Creates new form ScoutingUI
     */
    public ScoutingUI() {
        initComponents();
    }
    
    private int matchNumber;
    //===================auto vars=========================
    private boolean reachedSwitch = false;
    private boolean reachedScale = false;
    private boolean crossBaseline = false;
    private ArrayList<Integer> teamNumbers = new ArrayList<>(); //done
    private ArrayList<Integer> matchNumbers = new ArrayList<>(); //done
    private ArrayList<Integer> autoSwitchCubes = new ArrayList<>(); //done
    private ArrayList<Integer> autoScaleCubes = new ArrayList<>(); //done
    private ArrayList<Boolean> switchReaches = new ArrayList<>(); //done
    private ArrayList<Boolean> scaleReaches = new ArrayList<>(); //done
    private ArrayList<Boolean> baselineReaches = new ArrayList<>(); //done
    //=====================================================
    
    //===================tele vars=========================
    private ArrayList<Integer> teleSwitchCubes = new ArrayList<>(); //done
    private ArrayList<Integer> teleScaleCubes = new ArrayList<>(); //done
    private ArrayList<Integer> teleExchCubes = new ArrayList<>(); //done
    
    private ArrayList<Boolean> climbs = new ArrayList<>(); //done
    private ArrayList<Boolean> platforms = new ArrayList<>(); //done
    
    private boolean climbedPlatform = false;
    private boolean climbedScale = false;
    //=====================================================
    private ArrayList<ArrayList<Integer>> allData = new ArrayList<>();
    private String filePath;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        label1 = new java.awt.Label();
        matchNum = new java.awt.TextField();
        teamNum = new java.awt.TextField();
        label3 = new java.awt.Label();
        autoBaseline = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        autoSwitch = new javax.swing.JRadioButton();
        autoScale = new javax.swing.JRadioButton();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        submit = new javax.swing.JButton();
        autoScaleCubesPlaced = new javax.swing.JSlider();
        autoSwitchCubesPlaced = new javax.swing.JSlider();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        teleSwitchCubesPlaced = new javax.swing.JSlider();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        teleScaleCubesPlaced = new javax.swing.JSlider();
        label9 = new java.awt.Label();
        teleExchCubesPlaced = new javax.swing.JSlider();
        platform = new javax.swing.JRadioButton();
        climb = new javax.swing.JRadioButton();
        export = new javax.swing.JButton();
        fileName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FRC PowerUp Scouting");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        mainTitle.setBackground(new java.awt.Color(255, 255, 255));
        mainTitle.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        mainTitle.setForeground(new java.awt.Color(153, 0, 153));
        mainTitle.setText("FRC PowerUp Scouting");
        mainTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0), 5));

        label1.setText("Match");

        matchNum.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        label3.setText("Team");

        autoBaseline.setText("Baseline?");
        autoBaseline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoBaselineActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Auton");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0), 4));

        autoSwitch.setText("Reach switch?");
        autoSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoSwitchActionPerformed(evt);
            }
        });

        autoScale.setText("Reach scale?");
        autoScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoScaleActionPerformed(evt);
            }
        });

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        label5.setText("Switch cubes placed");

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        label6.setText("Scale cubes placed");

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        autoScaleCubesPlaced.setMajorTickSpacing(1);
        autoScaleCubesPlaced.setMaximum(10);
        autoScaleCubesPlaced.setMinorTickSpacing(1);
        autoScaleCubesPlaced.setPaintLabels(true);
        autoScaleCubesPlaced.setPaintTicks(true);
        autoScaleCubesPlaced.setSnapToTicks(true);
        autoScaleCubesPlaced.setValue(0);

        autoSwitchCubesPlaced.setMajorTickSpacing(1);
        autoSwitchCubesPlaced.setMaximum(10);
        autoSwitchCubesPlaced.setMinorTickSpacing(1);
        autoSwitchCubesPlaced.setPaintLabels(true);
        autoSwitchCubesPlaced.setPaintTicks(true);
        autoSwitchCubesPlaced.setSnapToTicks(true);
        autoSwitchCubesPlaced.setValue(0);

        jLabel3.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Teleop");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0), 4));

        teleSwitchCubesPlaced.setMajorTickSpacing(1);
        teleSwitchCubesPlaced.setMaximum(20);
        teleSwitchCubesPlaced.setMinorTickSpacing(1);
        teleSwitchCubesPlaced.setPaintLabels(true);
        teleSwitchCubesPlaced.setPaintTicks(true);
        teleSwitchCubesPlaced.setSnapToTicks(true);
        teleSwitchCubesPlaced.setValue(0);

        label7.setAlignment(java.awt.Label.CENTER);
        label7.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        label7.setText("Switch cubes placed");

        label8.setAlignment(java.awt.Label.CENTER);
        label8.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        label8.setText("Scale cubes placed");

        teleScaleCubesPlaced.setMajorTickSpacing(1);
        teleScaleCubesPlaced.setMaximum(20);
        teleScaleCubesPlaced.setMinorTickSpacing(1);
        teleScaleCubesPlaced.setPaintLabels(true);
        teleScaleCubesPlaced.setPaintTicks(true);
        teleScaleCubesPlaced.setSnapToTicks(true);
        teleScaleCubesPlaced.setValue(0);

        label9.setAlignment(java.awt.Label.CENTER);
        label9.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        label9.setText("Exchange cubes placed");

        teleExchCubesPlaced.setMajorTickSpacing(1);
        teleExchCubesPlaced.setMaximum(10);
        teleExchCubesPlaced.setMinorTickSpacing(1);
        teleExchCubesPlaced.setPaintLabels(true);
        teleExchCubesPlaced.setPaintTicks(true);
        teleExchCubesPlaced.setSnapToTicks(true);
        teleExchCubesPlaced.setValue(0);

        platform.setLabel("Platform?");
        platform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platformActionPerformed(evt);
            }
        });

        climb.setText("Climb?");
        climb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                climbActionPerformed(evt);
            }
        });

        export.setText("Export All Data");
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });

        jLabel1.setText("File Path");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainTitle)
                .addGap(60, 60, 60)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(matchNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teamNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(autoScale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(autoBaseline)
                            .addComponent(autoSwitch))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoSwitchCubesPlaced, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(autoScaleCubesPlaced, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(teleScaleCubesPlaced, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(teleSwitchCubesPlaced, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(submit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(export)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(climb)
                            .addComponent(platform)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teleExchCubesPlaced, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(118, 118, 118)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(588, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(mainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matchNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teamNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(autoBaseline)
                                        .addGap(7, 7, 7)
                                        .addComponent(autoSwitch))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(autoSwitchCubesPlaced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(autoScale))
                                        .addGap(22, 22, 22))
                                    .addComponent(autoScaleCubesPlaced, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(teleSwitchCubesPlaced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(teleScaleCubesPlaced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addComponent(teleExchCubesPlaced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(platform)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(climb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(submit)
                        .addComponent(export)))
                .addGap(32, 32, 32))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(447, Short.MAX_VALUE)))
        );

        matchNum.getAccessibleContext().setAccessibleName("");
        matchNum.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void autoBaselineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoBaselineActionPerformed
        
        if(crossBaseline == true)
        {
            crossBaseline = false;
        }
        else
        {
            crossBaseline = true;
        }
    }//GEN-LAST:event_autoBaselineActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        //===============================GENERIC GUI HANDLING==============================
        matchNumbers.add(Integer.parseInt(this.matchNum.getText()));        
        teamNumbers.add(Integer.parseInt(this.teamNum.getText()));
        
        //===============================AUTONOMOUS GUI HANDLING==============================               
        autoSwitchCubes.add(autoSwitchCubesPlaced.getValue());
        autoScaleCubes.add(autoScaleCubesPlaced.getValue());
        
        switchReaches.add(reachedSwitch);
        scaleReaches.add(reachedScale);
        baselineReaches.add(crossBaseline);
        //====================================================================================

        //==============================TELEOP GUI HANDLING===================================
        teleSwitchCubes.add(teleSwitchCubesPlaced.getValue());
        teleScaleCubes.add(teleScaleCubesPlaced.getValue());
        teleExchCubes.add(teleExchCubesPlaced.getValue());
        
        climbs.add(climbedScale);
        platforms.add(climbedPlatform);
        //====================================================================================
                
        //========resetting values to default code=============
        this.matchNum.setText(null);
        this.teamNum.setText(null);
        
        autoBaseline.setSelected(false);
        autoSwitch.setSelected(false);
        autoScale.setSelected(false);
        platform.setSelected(false);
        climb.setSelected(false);
        
        autoSwitchCubesPlaced.setValue(0);
        autoScaleCubesPlaced.setValue(0);
        teleSwitchCubesPlaced.setValue(0);
        teleScaleCubesPlaced.setValue(0);
        teleExchCubesPlaced.setValue(0);
        
        reachedSwitch = false;
        reachedScale = false;
        crossBaseline = false;
        
        climbedPlatform = false;
        climbedScale = false;
        //=====================================================
    }//GEN-LAST:event_submitActionPerformed

    private void autoSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoSwitchActionPerformed

        if(reachedSwitch == true)
        {
            reachedSwitch = false;
        }
        else
        {
            reachedSwitch = true;
        }
    }//GEN-LAST:event_autoSwitchActionPerformed

    private void autoScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoScaleActionPerformed
        
        if(reachedScale == true)
        {
            reachedScale = false;
        }
        else
        {
            reachedScale = true;
        }
    }//GEN-LAST:event_autoScaleActionPerformed

    private void platformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platformActionPerformed
        
        if(climbedPlatform == true)
        {
            climbedPlatform = false;
        }
        else
        {
            climbedPlatform = true;
        }
    }//GEN-LAST:event_platformActionPerformed

    private void climbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_climbActionPerformed
        
        if(climbedScale == true)
        {
            climbedScale = false;
        }
        else
        {
            climbedScale = true;
        }
    }//GEN-LAST:event_climbActionPerformed

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        //call CSV writing method here        

        filePath = this.fileName.getText();
        //construct a FileExport object using data from GUI
        FileExport f = new FileExport(
                teamNumbers,
                matchNumbers,
                autoSwitchCubes,
                autoScaleCubes,
                switchReaches,
                scaleReaches,
                baselineReaches,
                teleSwitchCubes,
                teleScaleCubes,
                teleExchCubes,
                climbs,
                platforms,
                allData
        );
        //consolidate data
        allData = f.get2DArr();        
        
        
        try
        {
            f.getIntCSV(allData,filePath); //make sure filepath has 2 \\ for between folders
        }
        catch (Exception ex) {
            System.out.println("Error");
        }
               
        //======================================================================
        //after data is exported, clear all of the arraylists so they don't
        //appear again in the csv file
        teamNumbers.clear();
        matchNumbers.clear();
        autoSwitchCubes.clear();
        autoScaleCubes.clear();
        switchReaches.clear();
        scaleReaches.clear();
        baselineReaches.clear();
        teleSwitchCubes.clear();
        teleScaleCubes.clear();
        teleExchCubes.clear();
        climbs.clear();
        platforms.clear();
    }//GEN-LAST:event_exportActionPerformed
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoutingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoutingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoutingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoutingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoutingUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton autoBaseline;
    private javax.swing.JRadioButton autoScale;
    private javax.swing.JSlider autoScaleCubesPlaced;
    private javax.swing.JRadioButton autoSwitch;
    private javax.swing.JSlider autoSwitchCubesPlaced;
    private javax.swing.JRadioButton climb;
    private javax.swing.JButton export;
    private javax.swing.JTextField fileName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private java.awt.Label label1;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JLabel mainTitle;
    private java.awt.TextField matchNum;
    private javax.swing.JRadioButton platform;
    private javax.swing.JButton submit;
    private java.awt.TextField teamNum;
    private javax.swing.JSlider teleExchCubesPlaced;
    private javax.swing.JSlider teleScaleCubesPlaced;
    private javax.swing.JSlider teleSwitchCubesPlaced;
    // End of variables declaration//GEN-END:variables
}
